CREATE_STATEMENTS = [

    # Stores every signal generated by the signal engine
    """
    CREATE TABLE IF NOT EXISTS signals (
        id              INTEGER PRIMARY KEY AUTOINCREMENT,
        ticker          TEXT NOT NULL,
        signal_type     TEXT NOT NULL,  -- MOMENTUM, REVERSION, BREAKOUT etc.
        direction       TEXT NOT NULL,  -- BUY, SELL, WATCH
        confidence      REAL NOT NULL,
        price_at_signal REAL NOT NULL,
        regime          TEXT,           -- BULL, BEAR, CHOPPY
        notes           TEXT,
        created_at      TEXT NOT NULL DEFAULT (datetime('now'))
    )
    """,

    # Stores every trade executed (real or paper)
    """
    CREATE TABLE IF NOT EXISTS trades (
        id              INTEGER PRIMARY KEY AUTOINCREMENT,
        signal_id       INTEGER,
        ticker          TEXT NOT NULL,
        direction       TEXT NOT NULL,  -- BUY, SELL
        quantity        REAL NOT NULL,
        price           REAL NOT NULL,
        total_value     REAL NOT NULL,
        currency        TEXT NOT NULL DEFAULT 'GBP',
        paper           INTEGER NOT NULL DEFAULT 1,  -- 1 = paper, 0 = live
        status          TEXT NOT NULL DEFAULT 'OPEN', -- OPEN, CLOSED, CANCELLED
        opened_at       TEXT NOT NULL DEFAULT (datetime('now')),
        closed_at       TEXT,
        pnl             REAL,
        notes           TEXT,
        FOREIGN KEY (signal_id) REFERENCES signals(id)
    )
    """,

    # Tracks daily portfolio snapshots for equity curve
    """
    CREATE TABLE IF NOT EXISTS portfolio_snapshots (
        id              INTEGER PRIMARY KEY AUTOINCREMENT,
        snapshot_date   TEXT NOT NULL UNIQUE,
        total_value     REAL NOT NULL,
        cash_balance    REAL NOT NULL,
        invested_value  REAL NOT NULL,
        daily_pnl       REAL,
        total_pnl       REAL,
        recorded_at     TEXT NOT NULL DEFAULT (datetime('now'))
    )
    """,

    # Stores backtest results for strategy comparison
    """
    CREATE TABLE IF NOT EXISTS backtest_results (
        id              INTEGER PRIMARY KEY AUTOINCREMENT,
        strategy_name   TEXT NOT NULL,
        ticker          TEXT,
        start_date      TEXT NOT NULL,
        end_date        TEXT NOT NULL,
        total_return    REAL,
        sharpe_ratio    REAL,
        max_drawdown    REAL,
        win_rate        REAL,
        total_trades    INTEGER,
        run_at          TEXT NOT NULL DEFAULT (datetime('now'))
    )
    """
]